name: Heroku Deploy

on:
  push:
    branches: [ main ]

jobs:

  DeployTrue:

    name: DeployTrue
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '+ DEPLOY')"

    steps:

      - name: Mark as successful run
        run: |
          true

  DeployFalse:

    name: DeployFalse
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '+ DEPLOY')"

    steps:

      - name: Mark as failed run
        run: |
          false
